name: Build LibreScroll

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Zig Compiler
      uses: mlugg/setup-zig@v1
      with:
        version: 0.13.0

    - name: Build Executable
      run: zig build -Doptimize=ReleaseFast

    - name: Upload Compiled Binary
      uses: actions/upload-artifact@v4
      with:
        name: LibreScroll-Custom-Build
        path: |
          zig-out/bin/
          zig-out/
